### ISSUE TITLE
Issues with joining a classroom and removing a student from classroom

### ISSUE THREAD

**Issue by srallen** [zooniverse/education-api#61]
On staging, my user, srallen086 (id `1756`), is joined to a classroom (id `264`) as a student that I am also the teacher of. When I try to delete myself from the classroom, it responds with a 500:

![screen shot 2017-09-12 at 2 38 33 pm](https://user-images.githubusercontent.com/5016731/30344725-1a30ed10-97c8-11e7-9f5e-bafb30ce34ac.png)

When I try to join as myself, I'd expect a 422 since I've already joined, but I see a 500:

![screen shot 2017-09-12 at 2 48 05 pm](https://user-images.githubusercontent.com/5016731/30345072-6fccc360-97c9-11e7-9786-221371f252dc.png)
![screen shot 2017-09-12 at 2 48 13 pm](https://user-images.githubusercontent.com/5016731/30345075-71fe5e28-97c9-11e7-9197-f46b97239cf2.png)

When I try to join user zootester1 (id `1325801`), it 422s even though the user is not listed as a student user in the serialized response of classroom id `264`:

![screen shot 2017-09-12 at 2 40 42 pm](https://user-images.githubusercontent.com/5016731/30344855-921a1f18-97c8-11e7-98c1-44bae04d897f.png)
![screen shot 2017-09-12 at 2 40 57 pm](https://user-images.githubusercontent.com/5016731/30344858-93dc26b6-97c8-11e7-911d-701454e0e3d0.png)

I am the only listed student of classroom id `264`:
![screen shot 2017-09-12 at 2 45 05 pm](https://user-images.githubusercontent.com/5016731/30344978-0a698314-97c9-11e7-9b98-c9c17e469259.png)

I am able to replicate all of this using Wildcam Labs locally, too. 

I have been able to successfully join a user to a classroom if I know for a fact that user has never joined that classroom (user group) before on Wildcam Labs.

This may actually a Panoptes issue, so if determined to be so, let me know and I can close this here and open an issue on Panoptes.

**Comment by zwolf** [comment]
The 500 is `ActiveRecord::RecordNotUnique`. If the controller gets a response from panoptes (any response), it will then try add the current student to the classroom's list of students, even if they're already in the classroom. Getting any insight into the call to panoptes is a huge pain. I think I found a couple request in greylog, but they just show 400s to `/api/v1/memberships` with the expected params but without any explanation. I checked the panoptes db and the user in question wasn't in that group already. The panoptes client gem isn't super friendly about local testing, but I'll see if I can recreate that request.

@marten any insight here?

**Comment by srallen** [comment]
For the issue of attempting to join my own classroom, this line short circuits the call to Panoptes: https://github.com/zooniverse/education-api/blob/master/app/operations/classrooms/join.rb#L25

It attempts to join the classroom as a student, but since I'm already join, I'd expect a 422.

For the issue of another user attempting to join, if the user has joined previously, but was deleted, the join relationship already exists in Panoptes' membership table, but in an inactive state. Currently the controller when attempting to join again does not check for this and tries to create the row again, but fails, hence the 422. What it should do is change the state back to active.

**Comment by zwolf** [comment]
Fixed by https://github.com/zooniverse/Panoptes/pull/2464
