### ISSUE TITLE
Serialize zooniverse user group id for classroom

### ISSUE THREAD

**Issue by srallen** [zooniverse/education-api#64]
I think @zwolf told me last week that the classroom id doesn't match the user group id on Panoptes. I will need the actual user group id to form the URL to the project because I'm writing the PFE project to use look for the query param with the group id to add the user group id to the classification metadata. Caesar will then use this user group id to group for the extractions and reductions. 

To be able to do this, I'll need the actual user group id to be serialized back with the classroom. I see a `groups` property in the relationships, but it appears to always be an empty array. Not sure what that's intended for.

**Comment by zwolf** [comment]
Added by #67
