### ISSUE TITLE
Associate existing Classrooms with a Wildcam program

### ISSUE THREAD

**Issue by zwolf** [zooniverse/education-api#66]
Planning on doing this in a separate PR/migration where I:
* create a new Wildcam program
* pull all the classrooms with a nil program and associate the Wildcam one.

Do I need a down migration for this? A rake task seems wrong for a one-off like this but so does the console but maybe this shouldn't be enshrined in a migration.

**Comment by srallen** [comment]
Done yesterday. Confirmed by @shaunanoordin that it's working as intended on production for wildcam-gorongosa-lab.
