### ISSUE TITLE
Auto assign endpoint for students for I2A

### ISSUE THREAD

**Issue by srallen** [zooniverse/education-api#68]
Currently the `/assignments?classroom_id=:classroom_id` endpoint returns assignments based on the type of user: teacher or student. This makes sense for privacy concerns, but doesn't quite fit the Intro2Astro use case.

Intro2Astro will always have the same three assignments per classroom. Because of this, when an I2A classroom is created, these three assignments are also created after successful classroom creation. At this point, no students are joined to the classroom.

The idea for the I2A workflow is that the I2A teacher creates the classroom which also creates the assignments, then sends out the join link. The student uses the join link which should then join them to the classroom and then join them to the classroom's assignments. The student joining the classroom's assignments does not work because the end point for the GET request for the classroom's assignments will return the currently assigned assignments and in this case that is none. I then can't iterate through the assignments response to send a PUT to update the `student_user` relationships.

To solve the I2A use case, I propose a special endpoint for auto-joining student users to the classroom that authenticates as the application. Perhaps something like `assignments/auto_join?classroom_id=:classroom_id`. This endpoint can take a classroom id, look up the linked assignments and then join the student user to all of them.

The alternative solution would be to _not_ auto-create the assignments on classroom creation, have the teacher send out the join link, the students join, and then have a button in the UI that the teacher can click to create the assignments once all of the expected students have joined. This seems like a less desirable solution because it may be more user error prone.

As an aside, when I try to auto-assign the assignments for classroom for the student user who also happens to be the teacher user of the classroom, the GET request for the assignments is successful, presumably because the teacher role gets checked first, but the PUT to update the assignment fails with a 422 with this reason:

<img width="326" alt="screen shot 2017-10-04 at 9 50 56 am" src="https://user-images.githubusercontent.com/5016731/31186940-d3752dde-a8f5-11e7-90b0-53bb33011bba.png">

This is an edge case, but it seems like supporting a teacher to join their own classroom as a student may have some issues that I can open separate github issues for. 

Pinging @marten for any more historical information about the design of the assignments operations. Let me know if a separate endpoint for auto-joining student users to the classroom assignments is a bad idea.

**Comment by marten** [comment]
Given that the workflows already exist, automatically linking students to assignments could happen when the student joins with no additional api calls. Just have the api link them up based on some config defined on the classroom or higher up?

- Marten

**Comment by srallen** [comment]
@zwolf That's a good idea too. Perhaps the `custom` property on the program can also give meaning to whether or not to auto-assign students when they join the classroom?

**Comment by zwolf** [comment]
Added by https://github.com/zooniverse/education-api/pull/73
